const swaggerJsdoc = require("swagger-jsdoc");

const options = {
    definition: {
        openapi: "3.0.0",

        info: {
            title: "PromptQL API",
            version: "1.0.0",
            description:
                "Natural language database query gateway supporting PostgreSQL, MySQL, SQLite, and MongoDB."
        },

        servers: [
            {
                url: "http://localhost:5000",
                description: "Local development server"
            }
        ],

        components: {

            securitySchemes: {

                ApiKeyAuth: {
                    type: "apiKey",
                    in: "header",
                    name: "x-api-key"
                }
            },

            schemas: {

                QueryRequest: {

                    type: "object",

                    required: [
                        "query",
                        "source"
                    ],

                    properties: {

                        query: {
                            type: "string",
                            example: "Show all users",
                            description:
                                "Natural language request describing the database operation."
                        },

                        source: {
                            type: "string",

                            enum: [
                                "postgres",
                                "mysql",
                                "sqlite",
                                "mongodb"
                            ],

                            example: "postgres",

                            description:
                                "Database type against which the query should be generated and executed."
                        }
                    }
                },


                QueryResponse: {

                    type: "object",

                    properties: {

                        success: {
                            type: "boolean",
                            example: true
                        },

                        query: {
                            type: "string",
                            example: "Show all users",
                            description:
                                "Original natural language request."
                        },

                        generatedQuery: {
                            type: "object",

                            description:
                                "Read-only query generated by the Hugging Face Qwen model.",

                            properties: {

                                type: {
                                    type: "string",
                                    enum: [
                                        "sql",
                                        "mongo"
                                    ],

                                    example: "sql"
                                },

                                query: {
                                    type: "string",
                                    example: "SELECT * FROM users",
                                    description:
                                        "Generated SQL query for PostgreSQL, MySQL, or SQLite."
                                },

                                operation: {
                                    type: "string",
                                    enum: [
                                        "find",
                                        "aggregate"
                                    ],

                                    example: "find",
                                    description:
                                        "MongoDB read operation."
                                },

                                collection: {
                                    type: "string",
                                    example: "users",
                                    description:
                                        "MongoDB collection."
                                },

                                filter: {
                                    type: "object",
                                    example: {},
                                    description:
                                        "MongoDB filter used for a find operation."
                                },

                                pipeline: {
                                    type: "array",
                                    example: [],
                                    description:
                                        "MongoDB aggregation pipeline."
                                }
                            }
                        },

                        data: {
                            type: "array",

                            items: {
                                type: "object"
                            },

                            example: [
                                {
                                    id: 1,
                                    name: "Sania",
                                    email: "sania@example.com"
                                }
                            ]
                        },

                        rowCount: {
                            type: "integer",
                            example: 1,
                            description:
                                "Number of records returned by the database."
                        }
                    }
                },


                ErrorResponse: {

                    type: "object",

                    properties: {

                        success: {
                            type: "boolean",
                            example: false
                        },

                        error: {

                            type: "object",

                            properties: {

                                code: {
                                    type: "string",
                                    example: "QUERY_NOT_SUPPORTED"
                                },

                                message: {
                                    type: "string",

                                    example:
                                        "The requested fields are not available in the provided schema."
                                }
                            }
                        }
                    }
                }
            }
        }
    },

    apis: [
        "./src/app.js"
    ]
};

const swaggerSpec =
    swaggerJsdoc(options);

module.exports = swaggerSpec;